spring:
  #---- Datasource Setting ----
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:whale}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:whale}

  #---- Spring Data Jpa Setting ----
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

#---- Logging Setting ----
logging:
  config: classpath:logback/logback-local.xml

# Auth Setting
jwt:
  secret: ${JWT_SECRET:fb0e5952-cccb-4ed2-9f67-eb2081a20433}
